server:
  servlet:
    context-path: "/payments-app"
  port: 8031

spring:
  application:
    name: payments-core

service:
  payment-client-products: "/products-app/v1/api/products/"

integration:
  clients:
    payments-properties:
      uri: "http://localhost:8989"
      connect-timeout: 5s
      read-timeout: 10s